CREATE TABLE IF NOT EXISTS "audit_logs" (
	"id" serial PRIMARY KEY NOT NULL,
	"property_id" text,
	"action" text NOT NULL,
	"user_name" text NOT NULL,
	"user_id" text,
	"old_value" text,
	"new_value" text,
	"created_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "database_backups" (
	"id" serial PRIMARY KEY NOT NULL,
	"backup_id" text NOT NULL,
	"file_name" text NOT NULL,
	"file_size" integer DEFAULT 0 NOT NULL,
	"record_count" integer DEFAULT 0 NOT NULL,
	"status" text DEFAULT 'Success' NOT NULL,
	"created_by_name" text NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "database_backups_backup_id_unique" UNIQUE("backup_id")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "import_history" (
	"id" serial PRIMARY KEY NOT NULL,
	"import_id" text NOT NULL,
	"file_name" text NOT NULL,
	"user_name" text NOT NULL,
	"user_id" text,
	"total_rows" integer DEFAULT 0 NOT NULL,
	"new_count" integer DEFAULT 0 NOT NULL,
	"updated_count" integer DEFAULT 0 NOT NULL,
	"skipped_count" integer DEFAULT 0 NOT NULL,
	"error_count" integer DEFAULT 0 NOT NULL,
	"status" text DEFAULT 'Completed' NOT NULL,
	"errors_json" jsonb DEFAULT '[]'::jsonb,
	"created_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "import_history_import_id_unique" UNIQUE("import_id")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "properties" (
	"id" serial PRIMARY KEY NOT NULL,
	"property_id" text NOT NULL,
	"title" text DEFAULT '' NOT NULL,
	"title_th" text,
	"address" text DEFAULT '' NOT NULL,
	"district" text DEFAULT 'Mueang Phuket' NOT NULL,
	"city" text DEFAULT 'Phuket' NOT NULL,
	"zone" text DEFAULT 'Zone 2',
	"area" text DEFAULT 'Rawai',
	"nation" text DEFAULT 'Thailand',
	"postal_code" text DEFAULT '83130',
	"category" text DEFAULT 'Villa' NOT NULL,
	"status" text DEFAULT 'Available' NOT NULL,
	"property_label" text DEFAULT 'Rent',
	"is_published" boolean DEFAULT false,
	"publish_status" text DEFAULT 'Draft',
	"price" numeric DEFAULT '0',
	"rent_price" numeric DEFAULT '0',
	"daily_rent" numeric DEFAULT '0',
	"bedrooms" integer DEFAULT 0,
	"bathrooms" integer DEFAULT 0,
	"usable_area" numeric DEFAULT '0',
	"land_area" numeric DEFAULT '0',
	"floor" integer,
	"year_built" integer,
	"furniture" text DEFAULT 'Fully Furnished',
	"pet_friendly" boolean DEFAULT false,
	"pet_type" text DEFAULT 'Pets Not Allowed',
	"pet_remark" text,
	"has_pool" boolean DEFAULT false,
	"has_house_pool" text DEFAULT 'No Pool',
	"pool_type" text DEFAULT 'No Pool',
	"owner_id" text,
	"owner_name" text DEFAULT '' NOT NULL,
	"owner_phone" text DEFAULT '' NOT NULL,
	"owner_email" text,
	"virtual_phone_1" text,
	"virtual_phone_2" text,
	"landlord_phone_3" text,
	"agent_id" text DEFAULT 'usr-1' NOT NULL,
	"agent_name" text DEFAULT 'Somchai Prasert' NOT NULL,
	"agency_type" text DEFAULT 'Co-Broke',
	"agency_from" text,
	"agency_to" text,
	"description" text DEFAULT '',
	"description_th" text DEFAULT '',
	"google_map_url" text,
	"amenities" jsonb DEFAULT '[]'::jsonb,
	"images" jsonb DEFAULT '[]'::jsonb,
	"videos" jsonb DEFAULT '[]'::jsonb,
	"featured" boolean DEFAULT false,
	"is_black_list" boolean DEFAULT false,
	"is_favorite" boolean DEFAULT false,
	"approval_status" text DEFAULT 'Pending',
	"villa_ownership" text,
	"land_ownership" text,
	"house_no" text,
	"building" text,
	"building_no" text,
	"room_no" text,
	"land_unit" text DEFAULT 'Sq.w',
	"usable_area_unit" text DEFAULT 'Sq.m',
	"project_name" text,
	"project_name_th" text,
	"property_type" text,
	"views" jsonb DEFAULT '[]'::jsonb,
	"check_list" jsonb DEFAULT '[]'::jsonb,
	"service_include" jsonb DEFAULT '[]'::jsonb,
	"location_info_th" text,
	"location_info_en" text,
	"comments" text,
	"deposit" text,
	"advance_payment" text,
	"commission" text,
	"sale_commission" text,
	"transfer_type" text DEFAULT '50/50',
	"common_fee" numeric DEFAULT '0',
	"electricity_bill" text,
	"water_bill" text,
	"landlord_contact_method" text,
	"landlord_id_number" text,
	"landlord_notes" text,
	"latitude" numeric,
	"longitude" numeric,
	"last_follow_up_date" text,
	"last_follow_up_status" text,
	"last_follow_up_content" text,
	"follow_up_records" jsonb DEFAULT '[]'::jsonb,
	"landlord_phone_records" jsonb DEFAULT '[]'::jsonb,
	"update_logs" jsonb DEFAULT '[]'::jsonb,
	"is_archived" boolean DEFAULT false NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "properties_property_id_unique" UNIQUE("property_id")
);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "prop_id_idx" ON "properties" USING btree ("property_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "prop_status_idx" ON "properties" USING btree ("status");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "prop_cat_idx" ON "properties" USING btree ("category");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "prop_agent_idx" ON "properties" USING btree ("agent_name");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "prop_zone_idx" ON "properties" USING btree ("zone");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "prop_area_idx" ON "properties" USING btree ("area");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "prop_archived_idx" ON "properties" USING btree ("is_archived");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "prop_created_idx" ON "properties" USING btree ("created_at");